name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 0.4.0-dev.5
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues
publish_to: none

environment:
  sdk: '>=2.12.0-259.9 <3.0.0'

dependencies:
  ffi: ^1.0.0
  # win32: ^2.0.0
  win32:
    path: ../win32

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
  test_coverage: ^0.5.0
