name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 1.0.5
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32: ^2.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9