name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 0.4.9
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32: ^2.0.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7