name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 1.0.0-pre.13
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.13.0-165.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32: ^2.1.0-pre.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3