name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 0.4.12
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.13.0-165.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32:
    git: 
      url: https://github.com/timsneath/win32.git
      ref: dart2.13

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

# While under development and the win32 dependency points to a git repo
publish_to: none