name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 0.3.0-dev.2
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.12.0-259.8 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32:
    path: ../win32

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0