name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      # We want to see the results even if one Dart version fails (and vice
      # versa). This prevents one failure from stopping the entire run.
      fail-fast: false

      matrix:
        os: [windows-latest, windows-2016]
        # sdk: [stable, dev]
        sdk: [beta, dev, main]

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{matrix.sdk}}

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-warnings

      - name: Run tests
        run: dart test
